"""initial_schema

Revision ID: 9d887db892c9
Revises: 
Create Date: 2026-04-15 08:12:43.789206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d887db892c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow', sa.Text(), nullable=False),
    sa.Column('cached_status', sa.Text(), nullable=True),
    sa.Column('eligible_activities', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('informed_by_activity_id', sa.UUID(), nullable=True),
    sa.Column('informed_by_uri', sa.Text(), nullable=True),
    sa.Column('computed_status', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint(
        '(informed_by_activity_id IS NULL) OR (informed_by_uri IS NULL)',
        name='ck_activities_informed_by_one_of',
    ),
    )
    op.create_index('ix_activities_dossier_id', 'activities', ['dossier_id'], unique=False)
    op.create_index('ix_activities_dossier_type', 'activities', ['dossier_id', 'type'], unique=False)
    op.create_index('ix_activities_type', 'activities', ['type'], unique=False)
    op.create_table('associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_associations_activity_id', 'associations', ['activity_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('derived_from', sa.UUID(), nullable=True),
    sa.Column('attributed_to', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schema_version', sa.Text(), nullable=True),
    sa.Column('tombstoned_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['derived_from'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['tombstoned_by'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_dossier_entity', 'entities', ['dossier_id', 'entity_id'], unique=False)
    op.create_index('ix_entities_dossier_id', 'entities', ['dossier_id'], unique=False)
    op.create_index('ix_entities_dossier_type', 'entities', ['dossier_id', 'type'], unique=False)
    op.create_index('ix_entities_dossier_type_created', 'entities', ['dossier_id', 'type', 'created_at'], unique=False)
    op.create_index('ix_entities_entity_id', 'entities', ['entity_id'], unique=False)
    op.create_index('ix_entities_generated_by', 'entities', ['generated_by'], unique=False)
    op.create_index('ix_entities_type', 'entities', ['type'], unique=False)
    op.create_table('activity_relations',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'entity_id', 'relation_type')
    )
    op.create_index('ix_relations_activity', 'activity_relations', ['activity_id'], unique=False)
    op.create_index('ix_relations_entity', 'activity_relations', ['entity_id'], unique=False)
    op.create_index('ix_relations_type', 'activity_relations', ['relation_type'], unique=False)
    op.create_table('used',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'entity_id')
    )

    # Partial index for the worker poll query:
    #   SELECT ... FROM entities WHERE type='system:task'
    #     AND content->>'status' = 'scheduled'
    # Without this, every poll cycle is a sequential scan of the
    # entities table. With it, Postgres walks only the rows that
    # are both system:task AND currently scheduled.
    op.execute(
        "CREATE INDEX ix_entities_scheduled_tasks "
        "ON entities ((content->>'status')) "
        "WHERE type = 'system:task' AND content->>'status' = 'scheduled'"
    )

    # Partial index for the dead-letter requeue query:
    #   SELECT ... FROM entities WHERE type='system:task'
    #     AND content->>'status' = 'dead_letter'
    op.execute(
        "CREATE INDEX ix_entities_dead_letter_tasks "
        "ON entities ((content->>'status')) "
        "WHERE type = 'system:task' AND content->>'status' = 'dead_letter'"
    )

    # Domain relations — semantic links between entities/URIs.
    op.create_table('domain_relations',
    sa.Column('id', sa.UUID(), nullable=False, default=sa.text('gen_random_uuid()')),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('from_ref', sa.Text(), nullable=False),
    sa.Column('to_ref', sa.Text(), nullable=False),
    sa.Column('created_by_activity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()')),
    sa.Column('superseded_by_activity_id', sa.UUID(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id']),
    sa.ForeignKeyConstraint(['created_by_activity_id'], ['activities.id']),
    sa.ForeignKeyConstraint(['superseded_by_activity_id'], ['activities.id']),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_rel_dossier', 'domain_relations', ['dossier_id'], unique=False)
    op.create_index('ix_domain_rel_type', 'domain_relations', ['relation_type'], unique=False)
    op.create_index('ix_domain_rel_from', 'domain_relations', ['from_ref'], unique=False)
    op.create_index('ix_domain_rel_to', 'domain_relations', ['to_ref'], unique=False)
    op.create_index('ix_domain_rel_active', 'domain_relations', ['dossier_id', 'superseded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_domain_rel_active', table_name='domain_relations')
    op.drop_index('ix_domain_rel_to', table_name='domain_relations')
    op.drop_index('ix_domain_rel_from', table_name='domain_relations')
    op.drop_index('ix_domain_rel_type', table_name='domain_relations')
    op.drop_index('ix_domain_rel_dossier', table_name='domain_relations')
    op.drop_table('domain_relations')
    op.execute("DROP INDEX IF EXISTS ix_entities_dead_letter_tasks")
    op.execute("DROP INDEX IF EXISTS ix_entities_scheduled_tasks")
    op.drop_table('used')
    op.drop_index('ix_relations_type', table_name='activity_relations')
    op.drop_index('ix_relations_entity', table_name='activity_relations')
    op.drop_index('ix_relations_activity', table_name='activity_relations')
    op.drop_table('activity_relations')
    op.drop_index('ix_entities_type', table_name='entities')
    op.drop_index('ix_entities_generated_by', table_name='entities')
    op.drop_index('ix_entities_entity_id', table_name='entities')
    op.drop_index('ix_entities_dossier_type_created', table_name='entities')
    op.drop_index('ix_entities_dossier_type', table_name='entities')
    op.drop_index('ix_entities_dossier_id', table_name='entities')
    op.drop_index('ix_entities_dossier_entity', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_associations_activity_id', table_name='associations')
    op.drop_table('associations')
    op.drop_index('ix_activities_type', table_name='activities')
    op.drop_index('ix_activities_dossier_type', table_name='activities')
    op.drop_index('ix_activities_dossier_id', table_name='activities')
    op.drop_table('activities')
    op.drop_table('dossiers')
    op.drop_table('agents')
    # ### end Alembic commands ###
