"""
Integration tests for `Repository.ensure_external_entity`.

External entities represent URIs that activities reference but the
engine doesn't own — for example, an erfgoedobject URL in the
heritage-permit workflow. When an activity uses or generates an
external URI, the engine materializes an `external`-typed entity
row so the URI shows up in the PROV graph. Same URI referenced
again must resolve to the same row, not create a duplicate —
otherwise PROV closure breaks (one logical external thing would
have multiple provenance identities) and the database grows
without bound.

The idempotency is implemented via a deterministic UUID: the
entity's `id` is `uuid5(NAMESPACE_URL, f"{dossier_id}:{uri}")`.
That formula gives us three properties worth locking in:

1. Same URI, same dossier → same row (identity).
2. Same URI, different dossier → different rows (the dossier_id
   is part of the UUID5 input, so each dossier gets its own
   external entity instance).
3. Different URI, same dossier → different rows.

Plus the row shape:
* `type == "external"`
* `content == {"uri": uri}`
* `entity_id == version_id` (externals have no version history —
   they're immutable by definition).
* `generated_by is None` (the URI isn't generated by any activity
   — it exists because activities reference it, not produce it).

These aren't speculative tests. The whole `used` phase relies on
`ensure_external_entity` being idempotent — `_resolve_explicit`
calls it once per external ref in the `used_items` list, and a
broken implementation would silently multiply entity rows on
every re-reference. The API suite uses external URIs in D1, D2,
D6, and others, so a broken implementation would show up as an
exploding entities table. But it wouldn't necessarily fail any
assertion, so "the table grows" is the kind of thing only a
dedicated test catches.
"""
from __future__ import annotations

from uuid import UUID

import pytest

from dossier_engine.db.models import Repository


D1 = UUID("11111111-1111-1111-1111-111111111111")
D2 = UUID("22222222-2222-2222-2222-222222222222")

URI_A = "https://id.erfgoed.net/erfgoedobjecten/60001"
URI_B = "https://id.erfgoed.net/erfgoedobjecten/60002"


class TestEnsureExternalEntity:

    async def test_first_call_creates_row(self, repo):
        """Baseline: first call with a brand-new URI creates the
        row with the canonical shape."""
        await repo.create_dossier(D1, "toelatingen")
        row = await repo.ensure_external_entity(D1, URI_A)
        await repo.session.flush()

        assert row.type == "external"
        assert row.content == {"uri": URI_A}
        assert row.entity_id == row.id  # externals: version_id == entity_id
        assert row.generated_by is None
        assert row.dossier_id == D1

    async def test_second_call_same_dossier_same_uri_returns_same_row(
        self, repo,
    ):
        """Idempotency property #1: two calls with the same URI
        in the same dossier return the same underlying row
        (identical entity_id and version_id). This is what
        prevents `used` from creating duplicate external entities
        when a client references the same URI twice in the same
        request."""
        await repo.create_dossier(D1, "toelatingen")
        first = await repo.ensure_external_entity(D1, URI_A)
        second = await repo.ensure_external_entity(D1, URI_A)
        await repo.session.flush()

        assert first.id == second.id
        assert first.entity_id == second.entity_id
        assert first.content == second.content

    async def test_same_uri_different_dossier_different_rows(self, repo):
        """Idempotency property #2: the dossier_id is part of the
        UUID5 input, so the same URI referenced in two different
        dossiers produces two distinct external entity rows —
        one per dossier. This is correct because the PROV graph
        is per-dossier: D1's `used` edges can't point at D2's
        entity rows."""
        await repo.create_dossier(D1, "toelatingen")
        await repo.create_dossier(D2, "toelatingen")

        in_d1 = await repo.ensure_external_entity(D1, URI_A)
        in_d2 = await repo.ensure_external_entity(D2, URI_A)
        await repo.session.flush()

        assert in_d1.id != in_d2.id
        assert in_d1.dossier_id == D1
        assert in_d2.dossier_id == D2
        # Content is the same URI — it's the row identity that
        # differs, not the semantic meaning.
        assert in_d1.content == in_d2.content == {"uri": URI_A}

    async def test_different_uris_same_dossier_different_rows(self, repo):
        """Idempotency property #3: different URIs in the same
        dossier produce different rows. This is the trivial case
        — if it ever failed, UUID5 would be broken."""
        await repo.create_dossier(D1, "toelatingen")

        row_a = await repo.ensure_external_entity(D1, URI_A)
        row_b = await repo.ensure_external_entity(D1, URI_B)
        await repo.session.flush()

        assert row_a.id != row_b.id
        assert row_a.content == {"uri": URI_A}
        assert row_b.content == {"uri": URI_B}
