"""
Activity-execution endpoints — single, batch, and per-workflow typed.

Three shapes:

* `PUT /dossiers/{id}/activities/{activity_id}` — generic single-
  activity execution. The client supplies `type` in the body so this
  one endpoint covers every activity in every workflow.
* `PUT /dossiers/{id}/activities` — batch execution. A list of
  activities runs in order inside one transaction. If any step fails,
  the whole batch rolls back and the error includes the batch index.
  Entities generated by earlier steps are visible to later ones via
  the engine's auto-resolve mechanism.
* `PUT /dossiers/{id}/activities/{activity_id}/{activity_type}` —
  per-workflow typed wrappers. One of these gets generated for every
  client-callable activity in every loaded workflow. Functionally
  identical to the generic single endpoint, but with the activity
  type baked into the URL and a rich OpenAPI description (built by
  `_typed_doc.py`) explaining what the activity does, what it
  requires, and what it generates.

All three call into the same `execute_activity` engine entry point.
The shared "resolve plugin + activity def" and "run with error
forwarding" patterns are factored into module-private helpers so each
endpoint body stays focused on its specific shape.
"""

from __future__ import annotations

from uuid import UUID

from fastapi import Depends, FastAPI, HTTPException

from ..auth import User
from ..db import Repository, get_session_factory
from ..engine import ActivityError, execute_activity
from ..plugin import Plugin, PluginRegistry
from ._errors import activity_error_to_http
from ._models import ActivityRequest, BatchActivityRequest, FullResponse
from ._typed_doc import build_activity_description


def register(
    app: FastAPI,
    *,
    registry: PluginRegistry,
    get_user,
    global_access,
) -> None:
    """Register activity execution endpoints on the FastAPI app.

    Sets up the generic single endpoint, the batch endpoint, and one
    typed wrapper per client-callable activity in every loaded
    workflow.
    """

    @app.put(
        "/dossiers/{dossier_id}/activities/{activity_id}",
        response_model=FullResponse,
        tags=["activities"],
        summary="Execute an activity",
    )
    async def put_activity(
        dossier_id: UUID,
        activity_id: UUID,
        request: ActivityRequest,
        user: User = Depends(get_user),
    ):
        if not request.type:
            raise HTTPException(
                422, detail="'type' is required on the generic endpoint",
            )
        plugin, act_def = _resolve_plugin_and_def(
            registry, request.type, request.workflow,
        )

        session_factory = get_session_factory()
        async with session_factory() as session:
            async with session.begin():
                repo = Repository(session)
                return await _run_activity(
                    repo=repo,
                    plugin=plugin,
                    act_def=act_def,
                    dossier_id=dossier_id,
                    activity_id=activity_id,
                    user=user,
                    role=request.role,
                    used=request.used,
                    generated=request.generated,
                    relations=request.relations,
                    remove_relations=request.remove_relations,
                    workflow_name=request.workflow,
                    informed_by=request.informed_by,
                )

    @app.put(
        "/dossiers/{dossier_id}/activities",
        tags=["activities"],
        summary="Execute multiple activities atomically",
        description=(
            "Execute multiple activities in order within a single "
            "transaction. If any activity fails, all are rolled back. "
            "Entities generated by earlier activities are visible to "
            "later ones via auto-resolve."
        ),
    )
    async def execute_batch_activities(
        dossier_id: UUID,
        request: BatchActivityRequest,
        user: User = Depends(get_user),
    ):
        session_factory = get_session_factory()
        async with session_factory() as session:
            async with session.begin():
                repo = Repository(session)
                results = []

                for item in request.activities:
                    plugin, act_def = _resolve_plugin_and_def(
                        registry, item.type, request.workflow,
                    )
                    try:
                        response = await _run_activity(
                            repo=repo,
                            plugin=plugin,
                            act_def=act_def,
                            dossier_id=dossier_id,
                            activity_id=UUID(item.activity_id),
                            user=user,
                            role=item.role,
                            used=item.used,
                            generated=item.generated,
                            relations=item.relations,
                            remove_relations=item.remove_relations,
                            workflow_name=request.workflow,
                            informed_by=item.informed_by,
                        )
                    except HTTPException as e:
                        # Re-raise with the batch position annotated.
                        # Forward structured payloads when present.
                        prefix = (
                            f"Activity '{item.type}' "
                            f"(#{len(results) + 1}) failed: "
                        )
                        if isinstance(e.detail, dict):
                            new_detail = {
                                **e.detail,
                                "detail": f"{prefix}{e.detail.get('detail', '')}",
                            }
                            raise HTTPException(e.status_code, detail=new_detail)
                        raise HTTPException(
                            e.status_code, detail=f"{prefix}{e.detail}",
                        )

                    # Flush so the next activity can see entities this
                    # one generated via auto-resolve.
                    await repo.session.flush()
                    results.append(response)

                # Return the full per-activity result list plus the
                # final dossier state.
                return {
                    "activities": results,
                    "dossier": results[-1]["dossier"] if results else None,
                }

    # Per-workflow typed wrappers.
    for plugin in registry.all_plugins():
        workflow_name = plugin.name
        for act_def in plugin.workflow.get("activities", []):
            if act_def.get("client_callable") is False:
                continue
            _register_typed_route(
                app=app,
                registry=registry,
                get_user=get_user,
                workflow_name=workflow_name,
                act_name=act_def["name"],
                act_label=act_def.get("label", act_def["name"]),
                act_desc=build_activity_description(act_def, plugin),
            )


def _register_typed_route(
    *,
    app: FastAPI,
    registry: PluginRegistry,
    get_user,
    workflow_name: str,
    act_name: str,
    act_label: str,
    act_desc: str,
) -> None:
    """Register one per-workflow typed route for `act_name`.

    Uses the generic `ActivityRequest` model and bakes the activity
    type into the URL. The response model and request shape are
    identical to the generic single endpoint — only the OpenAPI
    metadata (tag, summary, description) differs.
    """

    @app.put(
        f"/dossiers/{{dossier_id}}/activities/{{activity_id}}/{act_name}",
        response_model=FullResponse,
        tags=[workflow_name],
        summary=act_label,
        description=act_desc,
    )
    async def endpoint(
        dossier_id: UUID,
        activity_id: UUID,
        request: ActivityRequest,
        user: User = Depends(get_user),
    ):
        request.type = act_name
        if not request.workflow:
            request.workflow = workflow_name

        plugin, act_def = _resolve_plugin_and_def(
            registry, act_name, workflow_name,
        )

        session_factory = get_session_factory()
        async with session_factory() as session:
            async with session.begin():
                repo = Repository(session)
                return await _run_activity(
                    repo=repo,
                    plugin=plugin,
                    act_def=act_def,
                    dossier_id=dossier_id,
                    activity_id=activity_id,
                    user=user,
                    role=request.role,
                    used=request.used,
                    generated=request.generated,
                    relations=request.relations,
                    remove_relations=request.remove_relations,
                    workflow_name=request.workflow,
                    informed_by=request.informed_by,
                )

    # FastAPI uses function name for route uniqueness — without this,
    # every typed wrapper would collide on `endpoint`.
    endpoint.__name__ = f"typed_{act_name}"
    endpoint.__qualname__ = f"typed_{act_name}"


def _resolve_plugin_and_def(
    registry: PluginRegistry,
    activity_type: str,
    workflow_name: str | None,
) -> tuple[Plugin, dict]:
    """Find the plugin and activity definition for `activity_type`.

    Two paths:

    1. **Registered activity** — `registry.get_for_activity` knows
       which plugin owns this activity type. Returns immediately.
    2. **First-activity-on-new-dossier** — the activity hasn't been
       registered with the registry yet (because the dossier doesn't
       exist), so we fall back to the explicit `workflow_name` from
       the request body, look up the plugin, and walk its activity
       list for a matching `name`.

    Raises 404 if neither path resolves.
    """
    result = registry.get_for_activity(activity_type)
    if result is not None:
        return result

    if not workflow_name:
        raise HTTPException(
            404, detail=f"Unknown activity type: {activity_type}",
        )

    plugin = registry.get(workflow_name)
    if plugin is None:
        raise HTTPException(
            404, detail=f"Unknown workflow: {workflow_name}",
        )

    for a in plugin.workflow.get("activities", []):
        if a["name"] == activity_type:
            return plugin, a
    raise HTTPException(
        404, detail=f"Unknown activity: {activity_type}",
    )


async def _run_activity(
    *,
    repo: Repository,
    plugin: Plugin,
    act_def: dict,
    dossier_id: UUID,
    activity_id: UUID,
    user: User,
    role: str | None,
    used: list,
    generated: list,
    relations: list,
    remove_relations: list,
    workflow_name: str | None,
    informed_by: str | None,
) -> dict:
    """Call `execute_activity` with the standard argument set,
    forwarding any `ActivityError` to an `HTTPException` so FastAPI
    serializes it correctly.

    Centralizes the `[item.model_dump() for item in ...]` pattern
    that all three endpoints repeat — the engine takes plain dicts,
    not Pydantic models.

    Also the chokepoint for audit emission on writes: every activity
    execution emits exactly one audit event here. The two success
    actions (`dossier.created` for root, `dossier.updated` otherwise)
    differ by whether the activity is marked as dossier-creating in
    its workflow YAML — `can_create_dossier: true` means it's the
    entry-point activity that spawns a new dossier row (e.g.
    `dienAanvraagIn`). On authorization denial (`ActivityError` with
    code 403), we emit `dossier.denied` so SIEM sees both read-side
    denials (from `routes/access.py`) and write-side denials (from
    here) in one stream. Non-authorization errors (validation, 422,
    etc.) are not audited — those belong in the application log /
    Sentry, not the SIEM audit trail.
    """
    from ..audit import emit_audit

    is_root = bool(act_def.get("can_create_dossier"))
    action = "dossier.created" if is_root else "dossier.updated"

    try:
        result = await execute_activity(
            plugin=plugin,
            activity_def=act_def,
            repo=repo,
            dossier_id=dossier_id,
            activity_id=activity_id,
            user=user,
            role=role,
            used_items=[u.model_dump() for u in used],
            generated_items=[g.model_dump() for g in generated],
            relation_items=[r.model_dump(by_alias=True) for r in relations],
            remove_relation_items=[r.model_dump(by_alias=True) for r in remove_relations],
            workflow_name=workflow_name,
            informed_by=informed_by,
        )
    except ActivityError as e:
        # Write-side authorization denial: emit dossier.denied so this
        # shows up in the SIEM stream alongside read-side denials from
        # routes/access.py. Non-403 errors (validation, business rule
        # violations) are NOT audited — those are app-level concerns,
        # not security events.
        code = getattr(e, 'code', None)
        if code == 403:
            emit_audit(
                action="dossier.denied",
                actor_id=user.id,
                actor_name=user.name,
                target_type="Dossier",
                target_id=str(dossier_id),
                outcome="denied",
                dossier_id=str(dossier_id),
                reason=getattr(e, 'message', str(e)),
                activity_type=act_def.get("name"),
                activity_id=str(activity_id),
            )
        raise activity_error_to_http(e)

    # Success. One audit event per committed activity.
    emit_audit(
        action=action,
        actor_id=user.id,
        actor_name=user.name,
        target_type="Dossier",
        target_id=str(dossier_id),
        outcome="allowed",
        dossier_id=str(dossier_id),
        activity_type=act_def.get("name"),
        activity_id=str(activity_id),
    )
    return result
